name: Code quality

on:
  push:
  workflow_dispatch:

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install requirements
        run: |
          pip install flake8==3.7.9

      - name: Run linter
        run: |
          flake8 modules --count --max-line-length=127 --statistics --exclude=modules/ckanext-spatial
